/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufu.facom.perpim.view;

import br.ufu.facom.perpim.control.AlunoControl;
import br.ufu.facom.perpim.control.DisciplinaControl;
import br.ufu.facom.perpim.model.Aluno;
import br.ufu.facom.perpim.model.AlunoTableModel;
import br.ufu.facom.perpim.model.Disciplina;
import br.ufu.facom.perpim.model.DisciplinaTableModel;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Hugo
 */
public class Pesquisa extends javax.swing.JInternalFrame {

    private DisciplinaTableModel disciplinaTableModel = new DisciplinaTableModel();
    private AlunoTableModel alunoTableModel = new AlunoTableModel();
    
    private String semestre;
    private String disciplinaId;

    public Pesquisa() {
        initComponents();
        this.listaSemestre.setModel(new DefaultComboBoxModel(DisciplinaControl.getListaSemestre().toArray()));

        semestre = listaSemestre.getSelectedItem().toString();
        configurarTabelaDisciplina();

        tabelaDisciplina.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                int linhaSelecionada = tabelaDisciplina.getSelectedRow();
                if (linhaSelecionada != -1) {
                    disciplinaId = disciplinaTableModel.getListaDisciplina().get(linhaSelecionada).getID();
                    configurarTabelaAluno();
                }

            }
        });
    }

    public void configurarTabelaDisciplina() {
        List<Disciplina> listaDisciplina = DisciplinaControl.findBySemestre(semestre);
        disciplinaTableModel.setListaDisciplina(listaDisciplina);
        disciplinaTableModel.fireTableDataChanged();
    }

    public void configurarTabelaAluno() {
        List<Aluno> listaAluno = AlunoControl.findByDisciplina(disciplinaId);
        alunoTableModel.setListaAluno(listaAluno);
        alunoTableModel.fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        listaSemestre = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAluno = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaDisciplina = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botaoEditarDisciplina = new javax.swing.JButton();
        botaoEditarAluno = new javax.swing.JButton();

        setClosable(true);
        setTitle("Pesquisa");

        jLabel1.setText("Semestre:");

        listaSemestre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listaSemestreItemStateChanged(evt);
            }
        });

        tabelaAluno.setModel(alunoTableModel);
        tabelaAluno.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tabelaAluno);

        tabelaDisciplina.setModel(disciplinaTableModel);
        tabelaDisciplina.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tabelaDisciplina);

        jLabel2.setText("Disciplinas:");

        jLabel3.setText("Alunos:");

        botaoEditarDisciplina.setText("Editar Disciplina Selecionada");
        botaoEditarDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarDisciplinaActionPerformed(evt);
            }
        });

        botaoEditarAluno.setText("Editar Aluno Selecionado");
        botaoEditarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listaSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoEditarDisciplina))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoEditarAluno)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(listaSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoEditarAluno)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoEditarDisciplina)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaSemestreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listaSemestreItemStateChanged
        semestre = listaSemestre.getSelectedItem().toString();
        configurarTabelaDisciplina();
    }//GEN-LAST:event_listaSemestreItemStateChanged

    private void botaoEditarDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarDisciplinaActionPerformed
        int linhaSelecionada = tabelaDisciplina.getSelectedRow();
        if (linhaSelecionada != -1) {
            Disciplina disciplina = disciplinaTableModel.getListaDisciplina().get(linhaSelecionada);
            CadastroDisciplina cadDisc = new CadastroDisciplina(this,disciplina);
            this.getParent().add(cadDisc);
            cadDisc.setVisible(true);
        }
    }//GEN-LAST:event_botaoEditarDisciplinaActionPerformed

    private void botaoEditarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarAlunoActionPerformed
        int linhaSelecionada = tabelaAluno.getSelectedRow();
        if (linhaSelecionada != -1) {
            Aluno aluno = alunoTableModel.getListaAluno().get(linhaSelecionada);
            CadastroAluno cadAluno = new CadastroAluno(this,aluno);
            this.getParent().add(cadAluno);
            cadAluno.setVisible(true);
        }
    }//GEN-LAST:event_botaoEditarAlunoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEditarAluno;
    private javax.swing.JButton botaoEditarDisciplina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox listaSemestre;
    private javax.swing.JTable tabelaAluno;
    private javax.swing.JTable tabelaDisciplina;
    // End of variables declaration//GEN-END:variables
}
